version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      DEEPSEEK_URL: ${DEEPSEEK_URL:-https://api.deepseek.com}
      UPLOADS_PATH: "/app/static/uploads"
    volumes:
      - uploads:/app/static/uploads
      - sqlite_data:/app/db/sqlite
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - uploads:/usr/share/nginx/html/static/uploads:ro

volumes:
  uploads:
  sqlite_data: 