// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Comment struct {
	ID        string    `json:"id"`
	ThreadID  string    `json:"thread_id"`
	CreatedAt time.Time `json:"created_at"`
}

type CommentImage struct {
	ID        string    `json:"id"`
	CommentID string    `json:"comment_id"`
	Filename  string    `json:"filename"`
	Filepath  string    `json:"filepath"`
	CreatedAt time.Time `json:"created_at"`
}

type CommentTranslation struct {
	ID        string `json:"id"`
	CommentID string `json:"comment_id"`
	Language  string `json:"language"`
	Content   string `json:"content"`
}

type Thread struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Category  string    `json:"category"`
	CreatedAt time.Time `json:"created_at"`
}
