// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateCommentImage(ctx context.Context, arg CreateCommentImageParams) (CommentImage, error)
	CreateCommentTranslation(ctx context.Context, arg CreateCommentTranslationParams) (CommentTranslation, error)
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	GetThread(ctx context.Context, id string) (Thread, error)
	GetThreadComments(ctx context.Context, threadID string) ([]GetThreadCommentsRow, error)
	ListAllThreads(ctx context.Context) ([]Thread, error)
	ListThreads(ctx context.Context, category string) ([]Thread, error)
}

var _ Querier = (*Queries)(nil)
